### ISSUE TITLE
Discuss Uniswap V3 support

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#110]
**Goal:**
Have shared understanding of uniswap v3 support

**Context:**
As part of support for `WstETH` (see: #92) we started to use uniswap v3. 
Since there is another callee that helps to swap other collateral types with uniswap v3 as well (see: https://github.com/makerdao/exchange-callees/blob/master/src/UniswapV3Callee.sol), question is how much effort is left to include support for this callee. 
Underyling question: How to distinguish whether uniswap v2 or v3 callee to be used? 

**Tasks:**
- [ ] Discuss topic outlined in context section above in this issue
- [ ] Agree on next steps

**Comment by valiafetisov** [comment]
> how much effort is left to include support for this callee as well

I would say there are can be 2 steps:
1. Add usual support for the new callee: create functions `getCalleeData` and `getMarketPrice`. As correctly assumed, price fetching is touched upon in the #92. We just need to refactor it into a separate helper and take exchange routes into account. Auction-demo-keeper for example, just does it [in a loop](https://github.com/makerdao/auction-demo-keeper/blob/bca09252af029448ff67823b0b7825ad8c6feff8/src/dex/uniswapv3.js#L36-L45). So this step should not be more difficult than #92.

2. Investigate [Auto Router](https://uniswap.org/blog/auto-router) and first check if it's even possible to use it with the callee.

> Underyling question: How to distinguish whether uniswap v2 or v3 callee to be used?

We specify callee contract name in the collateral config, eg: https://github.com/sidestream-tech/unified-auctions-ui/blob/47fb9f41684431b1e48305a193bc9f9fa8861e4f/core/src/constants/COLLATERALS.ts#L10

By the way, do we want to switch all "standard" collaterals to the new callee? For some reason, auction-demo-keeper [still uses univ2 callee for `YFI-A` collateral](https://github.com/makerdao/auction-demo-keeper/blob/bca09252af029448ff67823b0b7825ad8c6feff8/config/mainnet.json#L183-L195), but not any other one. This maybe worth another investigation.
