### ISSUE TITLE
Integrate `WalletPopup` into the flow

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#136]
### Goal

Complete and working `Manage DAI in VAT` popup

### Context
After all underlying issues are done, this issue is to modify `BidTransaction` component to include new `WalletPopup` popup and connect it to the store. Note: the button `Manage DAI in VAT` is already in the code, you just need to uncomment it.

### Assets
- `Manage DAI in VAT` mock https://github.com/sidestream-tech/unified-auctions-ui/issues/126

### Tasks
- [ ] Add `Manage DAI in VAT` button
- [ ] Trigger popup
- [ ] Write `WalletContainer` logic that interacts with the store

**Comment by benediktkaiser** [comment]
> Note: the button `Manage DAI in VAT` is already in the code, you just need to uncomment it.

In Which file can I find this? I checked the BidTransaction components and the header. It was in neither file.

**Comment by LukSteib** [comment]
> In Which file can I find this? I checked the BidTransaction components and the header. It was in neither file.

Think you find it in the `DepositBlock.vue`. In the comment button is named `Manage VAT` so let's change that to `Manage DAI in VAT`.
