### ISSUE TITLE
Prevent flashloan executions for negative `Transaction Gross Profit`

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#157]
**Context:**
Reproducible in production: https://auctions.makerdao.network/collateral
Usually we do prevent a user from execution an auction via flashloan that still has a negative `Transaction Gross Profit`. 
We used to indicate this via red alert and prevented a user from execution.
This is no longer the case and needs to be fixed since execution yields an execution error in these cases.

**Tasks:**
- [x] Fix bug described above

**Assets:**
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/36229155/159513126-7ae4591a-bd95-4b8d-b5f1-4c8013d022be.png">

**Comment by valiafetisov** [comment]
This should've been closed by https://github.com/sidestream-tech/unified-auctions-ui/pull/167
