### ISSUE TITLE
Implement WithdrawCollateral block

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#170]
### Goal
User is able to withdraw collateral from VAT in one click

### Context
Since after the auction, the collateral is end up being stored in the VAT another block and a transaction if required in order for the user to withdraw collateral from VAT to the wallet.

### Assets
<img width="992" alt="Screenshot 2022-03-31 at 09 29 01" src="https://user-images.githubusercontent.com/3393626/161001388-c49a9085-844d-4db7-a60a-8c965972cccf.png">

### Tasks
- [ ] Add new `WithdrawCollateralBlock`
- [ ] Connect it to the store functions

**Comment by valiafetisov** [comment]
Proposed texts

- **Title:** Withdraw ${LINK} from the VAT
- **Content:** After participating in the auction, the collateral will end up in your VAT account. One more transaction is required to move it to your wallet.
- **Primary Active button:**  Withdraw ${10.00} ${LINK}
- **Primary Disabled button:** No collateral to withdraw
- **Secondary button:** Refresh ${LINK} balance in VAT

<img width="860" alt="Screenshot 2022-03-31 at 12 37 35" src="https://user-images.githubusercontent.com/3393626/161036457-09da2fd2-b1cf-41cd-ad90-e0980501ba26.png">

**Comment by LukSteib** [comment]
I like your proposal. Great first iteration for this feature. 

A thing we should keep in mind for the future (also related to the Dai based VAT management). IMO we should provide an interface for a user to interact with his funds in the VAT even though there is no active auction.
