### ISSUE TITLE
Fix tx fetch error

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#215]
**Context:**
Currently we are not able to fetch auction information on `mainnet`. See related error in assets section below. 

**Tasks:**
- [ ] Investigate and fix the fetching related error currently experienced on mainnet 

**Assets:**
```
fetch auction error Error: missing revert data in call exception (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":160,\"error\":{\"code\":-32000,\"message\":\"execution reverted\"}}","error":{"code":-32000},"requestBody":"{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x9b207afaaad1ae300ea659e71306a7bd6d81c160\",\"data\":\"0xe25fe175\"},\"latest\"],\"id\":160,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://mainnet.infura.io/v3/82bf6cb5d4ac4b119385ae8093a5d675"}, data="0x", code=CALL_EXCEPTION, version=providers/5.5.0)
    at y.makeError (a1f4023.js:2:25608)
    at y.throwError (a1f4023.js:2:25734)
    at ie (a1f4023.js:2:475962)
    at we.<anonymous> (a1f4023.js:2:484983)
    at Generator.throw (<anonymous>)
    at h (a1f4023.js:2:475601)
```

**Comment by valiafetisov** [comment]
Preliminary investigation:

The error is visible on the dashboard https://unified-auctions.makerdao.com/dashboard?network=mainnet
and is related to inability to fetch step/cut parameters for `TUSD-A` collateral

<img width="1005" alt="Screenshot 2022-04-19 at 16 28 01" src="https://user-images.githubusercontent.com/3393626/164027591-7f1bd63e-b0d2-402a-ab3f-aab8fc9eb2a1.png">

https://etherscan.io/address/0x9b207afaaad1ae300ea659e71306a7bd6d81c160

**Comment by valiafetisov** [comment]
The contract linked above was recently updated (2022-04-12) and seems to be missing `step` and `cut` parameters whatsoever, although being a "linear decrease" contract. Not sure how it's possible. For comparison, this is the regular `calc` contract https://etherscan.io/address/0x19e26067c4a69b9534adf97ed8f986c49179de18#readContract.

Do you have any information on how/why calc contracts was updated?

**Comment by valiafetisov** [comment]
This particular calc address was updated in the chainlog contract 36 minutes ago:

<img width="1071" alt="Screenshot 2022-04-19 at 16 38 48" src="https://user-images.githubusercontent.com/3393626/164029779-53514fae-9504-452a-ab03-a2ee6d443a28.png">

https://etherscan.io/address/0xdA0Ab1e0017DEbCd72Be8599041a2aa3bA7e740F#events

**Comment by valiafetisov** [comment]
Possible mitigations:
- `A` temporary hardcode old chainlog addresses (before recent update) instead of fetching them from the chainlink
- `B` temporary hardcode step/cut parameters for the `TUSD-A` in the collateral config and don't try to fetch them if they are present
- `C` fetch chainlink addresses on a specific block (we need a infura subscription with access to historical data for that)

The quickest and most stable one is option `A`. Option `C` is also a good one, but require new subscription. I will proceed to submit a PR for `A` for now

**Comment by LukSteib** [comment]
Probably this adjustment is part of the broader offboarding efforts for TUSD that were kicked off.
IMO as a short term measurement it is fine if we ensure that the UI is usable even if that means that TUSD is no longer supported at all.

For more infos on parameter updates see: https://forum.makerdao.com/t/proposed-parameters-for-offboarding-tusd-a/13506

**Comment by LukSteib** [comment]
Agree to first go with D
