### ISSUE TITLE
Deploy TUSD fix to `https://auctions.makerdao.network/`

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#219]
**Goal:**
Deploy hotfix

**Context:**
We had to release a small hotfix. 
As always the manual steps need to be made for domain: https://auctions.makerdao.network/
Release image: https://github.com/sidestream-tech/unified-auctions-ui/releases/tag/v1.1.1

**Tasks:**
- [ ] Deploy to `https://auctions.makerdao.network/`

**Comment by deusavalon** [comment]
Image tag `v1.1.1` got deployed to `https://auctions.makerdao.network/`

Please give it a quick test @LukSteib thx :)

**Comment by LukSteib** [comment]
> Please give it a quick test @LukSteib thx :)

Test successful 👍  - closing this issue
