### ISSUE TITLE
Do not refetch all auctions when only one is opened

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#223]
### Goal

Improve performance of the UI when user wants to participate in a single auction

### Context

Currently we're refetching all auctions every 30 seconds:
https://github.com/sidestream-tech/unified-auctions-ui/blob/f2e8f318e20c28a2d469c90139ad67c0f8af2ab6/frontend/store/auctions.ts#L19

And although it's not a simple interval, but 30 seconds between the end of the previous fetching and the next one (so that if the fetching itself takes more than 30 seconds, the UI is not overloaded), it's still too much in case there are a lot of active actions (eg > 100), which can compromise performance of the page itself, given all other enrichments we apply.

Instead, we should refetch only a single auction when the auction is "opened". This will also require us to better indicate what's happening, with both this auction and the auction table. Some initial ideas:
- Add indicator on the main page: above or below the table with auctions, when the auctions were fetched last time (and maybe even count down on when they will be refetched?)
- Move auctions table loading indicator from over the table to above/below around the last time fetch date (so it can also show refetching without disturbing the table itself)
- Darken the overlay or in other ways convey that auctions are not refetching
- Add indicator to the single auction page about the fetching date

### Implementation proposal
Implementation-wise this can be implemented completely in the store using `rootState.route.query` reactive state available in every store. The action `fetchWithoutLoading` can just check if `rootState.route.query.auction` is present and fetch only a single auction instead using something like `fetchAuctionByCollateralTypeAndAuctionIndex` + enrich it. We can also

### Tasks
- [x] create a mock
- [x] discuss, finalise
- [x] fetch only a single auction
- [x] implement UI improvements

**Comment by valiafetisov** [comment]
Proposal:
![MakerDAO@2x (6)](https://user-images.githubusercontent.com/3393626/164448739-dd64c2e9-24d2-4512-ab67-a4d71e9fb804.png)

**Comment by LukSteib** [comment]
> Add indicator on the main page: above or below the table with auctions, when the auctions were fetched last time

I like that idea in general and the two concrete mock proposals you made for that. Regarding the time till next refetch: It might be confusing to have both the indicator on last fetching AND the countdown till next planned fetching. What do you think about adding static info above or below table that indicates the refetching interval of 30sec? 

> Move auctions table loading indicator from over the table to above/below around the last time fetch date (so it can also show refetching without disturbing the table itself)

Cannot follow this point. The loading spinner (at least in my experience) is only shown when there is no auction data yet availble to be displayed in table (e.g. on first page load or hard refresh). Hence to me it is ok to keep it showing above the table. But maybe I do not really get what you mean. 

> Darken the overlay or in other ways convey that auctions are not refetching

Agree to increase contrast and further darken overlay. This hopefully implies to the user that only the active side panel contains latest information

> Add indicator to the single auction page about the fetching date

Agree and like the proposal to add it as an additional row to the auction table

**Comment by valiafetisov** [comment]
> What do you think about adding static info above or below table that indicates the refetching interval of 30sec?

I left this initial idea out of this concrete proposal, but I think that we can add this the same way as price drop indicator (ie animated circle with tooltip). Reasoning to include it in the table: it's actually an `expert` feature, so it should stay visible in the expert mode as well. But do you think we should implement this right away?

> The loading spinner (at least in my experience) is only shown when there is no auction data yet availble to be displayed in table (e.g. on first page load or hard refresh)

Yes, that's the current behaviour. But this issue proposes to display loading indication on every subsequent loading as well, to let the user know when data is actually being refetched, since if we apply proposed changes, there will be times when auctions do not get refetched, but the user wouldn't have a possibility to know the difference. I just want to avoid a situation when user feels that UI is broken and tries to refresh the whole page to get latest data.

**Comment by LukSteib** [comment]
> But do you think we should implement this right away?

I think it is fine to have the indicator when table was updated last for now and an indicator for the refetching to happen (ie. "Updating..."). The animated circle idea is a nice addition for the future.

> But this issue proposes to display loading indication on every subsequent loading as well

Got it and then I agree to the mock proposal. If we show loading indicator on subsequent loadings, let's not do it over the table but in the top right corner of the first row.
How about keeping the loading indicator over the table on first load and page refresh (since it makes clear to the user that auctions need to be fetched at least once to see anything in the table) and moving it to top row for subsequent loadings? 

One additional question:
Say a user opens the auction page for one particular auction. This means we would stop fetching all auctions but only keep on fetching information for this one particular auction. What happens when the user then switches back to the overall auction overview? Is a direct refetching triggered or will the user have to wait for 0-30 seconds up until next refetching?

**Comment by valiafetisov** [comment]
> How about keeping the loading indicator over the table on first load and page refresh (since it makes clear to the user that auctions need to be fetched at least once to see anything in the table) and moving it to top row for subsequent loadings?

As discussed in the daily: fine for me, but let's keep the props simple: only have one prop for loading and show loading overlay if there is no auctions (so not only on the first load)

> What happens when the user then switches back to the overall auction overview? Is a direct refetching triggered or will the user have to wait for 0-30 seconds up until next refetching?

Yes, it should be directly refetched as soon as the user switches back to the main page and `Updating...` indicator should be shown as proposed. It can be strange at times when user first opens a specific auction (eg from a twitter) and then navigates to the main page seeing only one auction there for 10 seconds till others are being fetched. Probably adding animation to the `Updating...` will attract enough user attention to let the user know that they have to wait.

**Comment by benediktkaiser** [comment]
> Probably adding animation to the `Updating...`

As we are passing `Updating...` to the [AntVue Table ](https://2x.antdv.com/components/table). Therefore we cannot simple just add an animation, as the column rows only take `strings` as their type. We would have to animate the string, unless there is another way.

**Comment by valiafetisov** [comment]
[According to the docs](https://2x.antdv.com/components/table), `Column` component accepts `title` as a slot, so it's definitely possible, but may require adding `Table.Column` to the template structure as we're not currently using it.

**Comment by valiafetisov** [comment]
#227 implemented only the UI parts, but actual fetching logic is not yet changed
