### ISSUE TITLE
Push redirect from auctions.makerdao.network

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#231]
**Goal:**
Establish a permanent redirect from `auctions.makerdao.network` to `unified-auctions.makerdao.com` 

**Context:**
Since we do not have access to the respective cloudflare account, setting the redirect properly needs to be coordinated with  SES. 
What we want to achieve: page rule for a 301 permanent redirect 
source: `auctions.makerdao.network`
target: `unified-auctions.makerdao.com` 
related guide: https://developers.cloudflare.com/pages/how-to/www-redirect/

**Tasks:**
- [x] Approach SES and ask for a page rule to redirect requests
- [ ] Check whether everything works as expected

**Comment by LukSteib** [comment]
Received the following screenshot as confirmation for page rule that was set by SES:
![Redirect](https://user-images.githubusercontent.com/36229155/165460873-b0f38c92-e7ef-468c-8cee-bcfb30d03d57.png)

However, redirect doesn't seem to work. 
Anything that might be configured wrong within cloudflare?

**Comment by valiafetisov** [comment]
The screenshot states `*.auctions.makerdao.network/` as a redirect source, which seems different from what we requested (`auctions.makerdao.network/*` -> `https://unified-auctions.makerdao.com/$1` according to the guide)

**Comment by LukSteib** [comment]
Update:

![image](https://user-images.githubusercontent.com/36229155/165738075-b64253d9-0d78-4bec-98f9-535a9473f7b8.png)

Tested and works now as expected.
Pls confirm @valiafetisov

**Comment by valiafetisov** [comment]
Yes, I confirm that old links correctly redirected, eg:
https://auctions.makerdao.network/collateral?network=mainnet&auction=UNIV2DAIETH-A%3A1

Let's create/reincarnate devops issue to transfer the bot and shut down the old cluster!

**Comment by LukSteib** [comment]
> Let's create/reincarnate devops issue to transfer the bot and shut down the old cluster!

As I am not fully aware of the current infra setup - can you create the issue for @deusavalon in order to not shut down things that shouldn't be shut down?
