### ISSUE TITLE
Stop computation of new approximateUnitPrice once auction is finished

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#24]
**Goal:**
Stop computation of price drop when auction is finished

**Context:**
In the past we have implemented a logic based on the parameters (`step` and `cut`) to compute price drops of an ongoing auction on our own and not rely on fetching the current auction price from the chain. See the following PR where this functionality was implemented: 
Retrieve Step/Cut sidestream-tech/auction-ui#279 
Include Step/Cut in design sidestream-tech/auction-ui#289

We figured that we keep on updating the Auction Price based on the `step` `cut` logic even after the auction is finished. This might cause confusion for user looking at a finished auction and seeing an auction price that is not similar to the actual price the auction was taken. 
See discrepancy in screenshot (our UI) and the respective finish price on makerburn for that exact auction (below)

**Tasks:**
- [ ] Quickly make yourself familiar with the `step` `cut` based logic to update price of an auction (see linked PRs above)
- [ ] Ensure that we do not update prices of auctions based on this logic once an auction is finished

**Assets:**
Screenshot of our UI
<img width="668" alt="Screenshot 2022-01-06 at 12 46 33" src="https://user-images.githubusercontent.com/36229155/148408234-05a45afe-75d3-4aed-8bc8-9bf2f126ae96.png">

Makerburn auction stats:
https://makerburn.com/#/liquidations/eth/271

**Comment by valiafetisov** [comment]
Please follow the review of the private PR which tried to solve this issue: https://github.com/sidestream-tech/auction-ui/pull/379#discussion_r785760205
