### ISSUE TITLE
Add continuous deployment into separate production cluster

### ISSUE THREAD

**Issue by BracketJohn** [sidestream-tech/unified-auctions-ui#25]
**Goal**

Also continuously deploy production at `auctions.makerdao.network`.

**Context**

sidestream-tech/auction-ui#363 set the baseline helm charts for continuous deployments and added the continuous deployment to `main.auction-ui.k8s.sidestream.tech`.

Merging sidestream-tech/auction-ui#363 will show if that actually worked, the goal if this issue is to then add a step to continuously deploy into the production cluster on a tag event (triggered via a github release for example).

**Tasks**

- [x] resolve any problems that occured during the deployment triggered by the merge of sidestream-tech/auction-ui#363
- [ ] add a continuous deployment step into the production cluster

**Comment by BracketJohn** [comment]
I want to already enable a deployment step that performs the production deployment (but listens to a different domain). A problem I see with this is the infura quota - we would have three environments continuously polling then:
- main
- auctions.makerdao.network
- production (later to become auctions.makerdao.network)

Do you see any way to remedy this @valiafetisov? We could for example set the infura polling time to something very high, as done in #30

**Comment by valiafetisov** [comment]
> Do you see any way to remedy this @valiafetisov?

Yes, you can 
- set `REFETCH_INTERVAL` to be very high (but not higher than `2147483647`, [they say](https://stackoverflow.com/a/3468650))
- skip setting `TWITTER_*` env variables for this new environment. In this case, twitter will fail with an error message in the logs and print an error every time tweet suppose to be published
https://github.com/sidestream-tech/unified-auctions-ui/blob/f5caae5077444b8cb0aa30cd52b91eba770ed656/bot-twitter/src/twitter.ts#L20 https://github.com/sidestream-tech/unified-auctions-ui/blob/f5caae5077444b8cb0aa30cd52b91eba770ed656/bot-twitter/src/twitter.ts#L38

**Comment by BracketJohn** [comment]
Thanks - please check the values with:
- `secret list auction-ui/production.auction-ui.k8s.sidestream.tech/bot-twitter -e`
- `secret list auction-ui/production.auction-ui.k8s.sidestream.tech/frontend -e`

I:
- remove twitter keys
- increased `REFETCH_INTERVAL`
- set `auction-ui/production.auction-ui.k8s.sidestream.tech/fronten production_domain` to `production.auction-ui.k8s.sidestream.tech`

**Comment by valiafetisov** [comment]
Everything looks good, but don't forget to add new origins to the production infura key (ending with `75`)
```
https://production.auction-ui.k8s.sidestream.tech
https://unified-auctions.makerdao.com
```
Probably @florianstoecker can help you with that 🙂

**Comment by florianstoecker** [comment]
What exactly do you need here? 
The infura projectID, the endpoint address, or the secret? And for which purpose (Twitter Bot production/ UI Production)?

**Comment by BracketJohn** [comment]
We need to add allowed origins to existing keys!

**Comment by valiafetisov** [comment]
We need to modify twitter bot production infura key (ending with `75`) to add new origins from above

**Comment by florianstoecker** [comment]
The one ending with 75 is the UI - production. Twitter Bot-production ends with 37

**Comment by valiafetisov** [comment]
Edited

**Comment by florianstoecker** [comment]
Alright, added the domains to the allowlist! 👍
