### ISSUE TITLE
Fix Mobile Format Bugs

### ISSUE THREAD

**Issue by florianstoecker** [sidestream-tech/unified-auctions-ui#27]
**Goal**
Make the UI mobile responsive.

**Context**
While testing the UI on real-world auctions, I found some formatting bugs/weird line splitting. See the Assets

**Tasks**
- [x] Make the UI mobile responsive

**Assets**
<details>
  <summary>Asset 1</summary>
  
  ![IMG_0810](https://user-images.githubusercontent.com/36764271/149084389-e166dfe4-d132-489c-859a-2223a56205bd.PNG)
  
</details>

<details>
  <summary>Asset 2</summary>
  
![IMG_0811](https://user-images.githubusercontent.com/36764271/149084401-4ea788c7-b7c1-4427-a7ae-b16a1a005b5e.PNG)
  
</details>

**Comment by benediktkaiser** [comment]
This was already merged in https://github.com/sidestream-tech/auction-ui/pull/373. It is also present in this code base. I think we can therefore close this issue.

**Comment by LukSteib** [comment]
> This was already merged in sidestream-tech/auction-ui#373. It is also present in this code base. I think we can therefore close this issue.

Good catch - closed
