### ISSUE TITLE
Create surplus auctions mock

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#288]
### Goal

Mock the whole process of participating in a surplus auction

### Context

Since investigation clarified some unknowns, we should be able to create a mock to further plan implementation of surplus auctions.

### Assets

Whimsical page https://whimsical.com/makerdao-surplus-VCnH8iCNcFUF3BYUcx7WmN

### Tasks

- [x] Create mock
- [x] Discuss

**Comment by valiafetisov** [comment]
![MakerDAO surplus@2x](https://user-images.githubusercontent.com/3393626/173034390-d17b639f-5d3b-4871-ba93-66129576ab79.png)

**Comment by LukSteib** [comment]
> Discuss

Commented directly in whimsical

**Comment by LukSteib** [comment]
>  Should we just show them directly in MKR per DAI instead of DAI per MKR? Any objections?

I would suggest to keep displaying them in `DAI per MKR`. This is more intuitive. An MKR holder (ie. a user entitled to participate in this type of auctions) thinks about MKR price in $ (and hence DAI) figures. So 880 `DAI per MKR` is more relatable and comparable than having something like 0.0013 `MKR per DAI`

**Comment by valiafetisov** [comment]
Ok, it's actually a bit misleading since market price to change MKR to DAI is different from DAI to MKR. So under the hood we would need to fetch the opposite to later convert it back.

Then do we change the color coding to be the opposite? Or do we simply show market difference based on the `MKR per DAI` internal value?

**Comment by LukSteib** [comment]
Ok after thinking about it for quite some time we might indeed go with `MKR per DAI` as the market price denomination. We might also think about changing the auction price to this denomination as well. Then we can in line with collateral auctions name the column in auctions table "Market Difference" and keep the known color coding (ie. green as long as the auction price in `MKR per DAI` is below market price. 

We then just need to account for the fact that we need to display a lot of decimal places (imagine first bid is 0.5 MKR for the 30k DAI that are auctioned off -> would result in an auction price of 0,000016 `MKR per DAI` )

**Comment by valiafetisov** [comment]
<details><summary>MKR per DAI mock</summary>

![MakerDAO surplus@2x (3)](https://user-images.githubusercontent.com/3393626/174849649-5a1deb64-19e5-4b2f-97d1-200eaa3908b3.png)

</details>

**Comment by LukSteib** [comment]
> Do you notice anything else I should change to finalise the mock?

I am still wondering wether there is a chance to somewhere additionally indicate the price for 1 MKR in DAI based on the current highest bid. Just as an "extra" info.

**Comment by valiafetisov** [comment]
Something like that?

![MakerDAO surplus@2x (5)](https://user-images.githubusercontent.com/3393626/174967540-6b3bed1b-5f5f-442e-9d7a-7ec8914b15ab.png)

**Comment by LukSteib** [comment]
> Oh, I think this would be confusing to mix up the units.

Yes true. Let's leave it as is. I like the idea of having the general switch - but we can put in in the backlog and tackle in one of the next iterations. Let's focus on the `MKR per DAI` case for now then as discussed yesterday
