### ISSUE TITLE
Fix fetching of past auctions

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#290]
### Goal
Correctly fetch auction information for past auctions (ie. auctions that are no longer active)

### Context
When directly accessing an auction via link (e.g. https://t.co/aOYK9wqPJE) and this auction is no longer available (ie. auction was taken in the past) the UI currently becomes unresponsive. See screencast below. 
For active auctions (or those that require restart) everything seems to work as expected. 
Tested on both networks
* main
* goerli

Assumption on my side: It is related to our new approach on how to fetch auctions...

### Tasks
- [ ] Investigate and fix problem above

### Assets
https://www.loom.com/share/858f924c6adb461bb3ed99c12ca7729d

**Comment by valiafetisov** [comment]
Confirmed that this problem appears right after https://github.com/sidestream-tech/unified-auctions-ui/pull/251 was merged
