### ISSUE TITLE
Decrease polling interval to save infura quota

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#30]
### Goal
Use less infura quota, but keep production bot functional

### Context
Currently, there are two bots, one in production (running on the mainnet) the other one is on staging (running on kovan) They both poll all auctions every minute, generating ~450K requests per day. Polling interval can be set via `REFETCH_INTERVAL` env variable (which accepts milliseconds).

https://github.com/sidestream-tech/auction-ui/blob/fcb68c2fe53607e2ccd8ecc8d3fd4acc39a216bb/bot-twitter/src/index.ts#L5

Please note that `REFETCH_INTERVAL` should not be too close to `THRESHOLD_FOR_NEW_AUCTIONS / 2` otherwise the auction may not be considered new (and sometimes fetching also fail).
https://github.com/sidestream-tech/auction-ui/blob/fcb68c2fe53607e2ccd8ecc8d3fd4acc39a216bb/bot-twitter/src/auctions.ts#L4

Maybe `THRESHOLD_FOR_NEW_AUCTIONS` should not be hardcoded, but rather calculated as something like `REFETCH_INTERVAL * 3`?

### Tasks
- [x] increase `REFETCH_INTERVAL` via env variable to let's say `120000` (2 minutes) in production
- [x] increase `REFETCH_INTERVAL` for staging or completely disable twitter bot there

**Comment by BracketJohn** [comment]
@valiafetisov was this fixed? What info do you need to verify?

**Comment by valiafetisov** [comment]
Yeah, I've changed it myself some time in the last sprint. The issue can be closed
