### ISSUE TITLE
Research integration testing

### ISSUE THREAD

**Issue by KirillDogadin-std** [sidestream-tech/unified-auctions-ui#325]
### Goal

Come up with a way to introduce integration tests

### Context

Currently there is no testing capabilities created for the software. To assure that the functionality works as expected, integration testing is required. This issue focuses on
- the research and proposals on how to implement/introduce it and 
- to which extend should the testing be introduced (e.g. should vuex store on frontend be somehow covered)

### Tasks

- [x] Suggest the scope to which the tests should be introduced.
- [x] Suggest the approach to testing.

**Comment by KirillDogadin-std** [comment]
- I would introduce the integration tests in a step-by-step manner to assure that there's not more test-writing requirements than needed.
  - that would imply that the bare minimum for the integration tests would be to cover `core` package with tests because the frontend vuex store heavily relies on its logic while itself does not perform the blockchain related operations. (aka communication with the blockchain is done through `core` on `frontend`)
- I would go with the simpliest approach and utilize the already present functionality of hardhat package. 
 - PROs:
   - rather easy to spin up locally
   - does not require many containers to work during CI-CD (could be done via having just `hardhat` as side service that holds the blockchain and the tests run against it
   - it is clear how to jumb between blocks and reset the test-chain
 - CONS:
   - we already have a package with hardhat installed in it, but still will have to install hardhat dependency into the `core` because it has to be able to reset the hardhat chain
     - alternatively we can import the `core` into `hardhat` and have tests there, but then tests and the source code are in different packages.
 ___
The implementation flow would go like this:
  - add the hardhat dependency into the `core`
  - add `test/` directory into the core
  - populate the test direcotry with the tests (`chai`)
    - use the `hre.network.provider.request` to call `hardhat_reset` method

then the tests in the core can be run with `npx hardhat --network localhost test` if the hardhat is running locally

That would allow to run the CI/CD where:

  - the core is now an image in which the command for tests is running
  - the hardhat is the service that the core-image depends on.

---

__Actionables for this post are at least the following__

1. comment on the suggestion to add the integration tests for core only
2. comment on the implementation suggestion
3. comment on the "put tests into hardhat package with installing core" vs "put tests into core and install hardhat" 
  - the suggestion is to do the latter
4. comment on the ci/cd layout

the very nasty demo of how the test file would look like can be found in https://github.com/sidestream-tech/unified-auctions-ui/pull/324/commits/23b6dace03fbde57404a357bc922436492bc9b5f

**Comment by valiafetisov** [comment]
> comment on the suggestion to add the integration tests for core only

Sounds like a good start and also a good place to store tests, next to the code itself.

> comment on the implementation suggestion
> comment on the "put tests into hardhat package with installing core" vs "put tests into core and install hardhat"

The only problem here is the ci/cd that till now wasn't building core as a separate image as far as I'm aware.

> comment on the ci/cd layout

The provided commit doesn't contain any CI/CD code. I would suggest to keep this very simple test and try to make CI/CD working!
