### ISSUE TITLE
Research metamask-related wallet connection bug

### ISSUE THREAD

**Issue by KirillDogadin-std** [sidestream-tech/unified-auctions-ui#326]
### Goal

Understand the reason and implement a fix for the wallet connection bug

### Context

https://github.com/sidestream-tech/unified-auctions-ui/pull/323#issuecomment-1170891605 reported the bug where the error arises. This error is due to metamask extension not injecting the object with the `isConnected` function. So, the code expects the function to exist and it does not.

### Assets

https://github.com/sidestream-tech/unified-auctions-ui/pull/323#issuecomment-1170891605

### Tasks

- [ ] Investigate and reproduce
- [ ] Suggest fix
- [ ] imlement the fix

**Comment by KirillDogadin-std** [comment]
@LukSteib , i fail to reproduce. Please provide additional context - go to your browser extenstions overview and post the info it provides you about the metamask. It includes version as well.

**Comment by LukSteib** [comment]
This is the metamask version I am using: 

<img width="600" alt="image" src="https://user-images.githubusercontent.com/36229155/176643040-e7949838-830a-4b46-b339-c3d60893277d.png">

Steps:
1. Open https://unified-auctions.makerdao.com/collateral?network=mainnet
2. Click "Connect Wallet" button in header
3. Select Metamask
4. Error is thrown (independent of whether one is logged in to metamask already via the extension or not yet)

Error message:
```
Uncaught (in promise) TypeError: window.ethereum.isConnected is not a function
    at Function.get (eea33d7.js:1:1389812)
    at eea33d7.js:1:1379266
    at j (1d4298d.js:2:72248)
    at Generator._invoke (1d4298d.js:2:72036)
    at forEach.t.<computed> [as next] (1d4298d.js:2:72428)
    at r (1d4298d.js:2:133)
    at l (1d4298d.js:2:336)
    at 1d4298d.js:2:395
    at new Promise (<anonymous>)
    at 1d4298d.js:2:276
```

Other than that what else do you need to work on this?

**Comment by KirillDogadin-std** [comment]
We have the exact same version of the metamask , i do the reproduction steps and no error is thrown, the wallet is connected.

**Comment by LukSteib** [comment]
Chrome browser version: 
<img width="600" alt="image" src="https://user-images.githubusercontent.com/36229155/176645292-a772b38c-1e07-43b6-88a9-06a35e8e2d67.png">

**Comment by LukSteib** [comment]
in the console?

`Uncaught TypeError: Cannot read properties of undefined (reading 'isConnected')`

**Comment by KirillDogadin-std** [comment]
i would then also ask you to try out [the above](https://github.com/sidestream-tech/unified-auctions-ui/issues/326#issuecomment-1171019930) after you do `await window.ethereum._initializeState()` beforehand.

**Comment by LukSteib** [comment]
> i would then also ask you to try out https://github.com/sidestream-tech/unified-auctions-ui/issues/326#issuecomment-1171019930 after you do await window.ethereum._initializeState() beforehand.

this already results in error: `Uncaught TypeError: window.ethereum._initializeState is not a function`
