### ISSUE TITLE
Display finished auction

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#33]
### Goal
An auction should be available by its link even after it was finished

### Context
Currently, we only fetch and display current auctions – auctions that are active or ones that need a restart. That results in a problem that as soon as an auction is taken by someone, our link to it (`/collateral?network=kovan&auction=BAL-A%3A`) is broken and currently shows `This auction was not found`, which is misleading.

In this issue we need to first investigate different ways to fetch auctions by id (without a need cache them ourselves). Otherwise:
- Subscribe/fetch clipper events (`Kick`, `Take`, `Redo`)
- Enrich event data to the minimal `Auction` type (as an event only contains `(index_topic_1 uint256 id, uint256 top, uint256 tab, uint256 lot, index_topic_2 address usr, index_topic_3 address kpr, uint256 coin)`)
- Store auctions in a database (setup database service)
- Update frontend auction page to fetch the auction from db (if the auction is not found or maybe always)

### Todo
- [ ] Investigate, write down a conclusion
- [ ] Implement caching or direct fetching

**Comment by benediktkaiser** [comment]
After a call with Valia the following steps must be taken to retrieve finished Auctions:

1.) Get the  clip contract of the Collateral (eg. [MCD_CLIP_ETH_A](https://kovan.etherscan.io/address/0x7dd1fb6b9afdba9f28db89c81723b8c6b27a2fbe#events))
2.) Get  the previous [events](https://docs.ethers.io/v5/concepts/events/)
3.) Filter them for the AuctionID we are searching for (using topics)
4.) Match the returning Auction Object with the one we are using in our UI
5.) Save the Auction to the store and display in the UI


Question:
Should the finished Auction then also be displayed in the table? Or only when you opened it via link?

**Comment by valiafetisov** [comment]
I've outlined the flow, I hope it also answers your question:

1. User opens `/collateral?network=kovan&auction=LINK-A%3A199` link
2. The page waits for the usual fetching to finish
3. When the loading finished and the auction not found, instead of displaying "not found" the component emits `fetchFinishedAuction('LINK-A:199')` to the container
4. The container triggers the store action that calls `fetchFinishedAuction` in the `core` and stores result in the `auctionStorage`
5. `fetchFinishedAuction(network, id)`
    - gets clipper contract address
    - fetches events filtered by the topic (encoded `Take`) `AND` the id (encoded 199)
    - converts fetched event data to our format (eg `price`->`unitPrice`, `tab`->`debtDAI`, you can isolate this part from `fetchAuctionStatus`)
    - returns Auction or throws an error
6. The UI shows not found or the finished auction (should happens automatically, if auction is in `auctionStorage`)

**Comment by valiafetisov** [comment]
With `convertNumberTo32Bytes`!

**Comment by benediktkaiser** [comment]
> convertNumberTo32Bytes

This function only takes in numbers, however auction IDS are strings. What do I do?

**Comment by valiafetisov** [comment]
> splits idFoundInURL into collateralType and auctionId, validates them (and throw error if they are invalid)

You can make a helper function (which also validates and throws errors if url parameter is invalid)
```js
[ collateralType: string, auctionId: number ] = parseAuctionURL(id);
```

**Comment by valiafetisov** [comment]
After the investigation, we learned:
- We can fetch `Take` events without a problem
- There are can be several take events per auction (due to the partial bidding)
- The event data doesn't contain auction data at that time, but rather data of the auction _after the execution_, therefore we can't show the event data itself
- There is a possibility to fetch auction data from a specific block, but it requires historical RPC node

Based on the above, especially the problem with multiple events per auction, it seems that it's not feasible to show auction table, like in a finished auction. Instead, we want to just fetch events and display them as transaction links.

The flow stays the same: if the auction is not found inside the active auctions, the component executes another action to fetch events. The events are populated into a new `auctionEvents` store and then filtered by the component
- If events loading is finished and there are no events, we show `This auction was not found` as before
- If events are found, we show list of events with the title `This auction was taken via X transactions:` and then provide a list of transactions with the links to etherscan
