### ISSUE TITLE
Deploy Release v1.5.0

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#331]
### Goal
Deploy release v1.5.0 to production

### Context
Latest changes will be deployed to production

### Tasks
- [x] Check staging
- [x] Create release images
- [x] check production

**Comment by LukSteib** [comment]
Anything else to check than existing functionality still working on staging for the #330 @valiafetisov ?

**Comment by valiafetisov** [comment]
Technically we may want to check the the bot is active, at least using its logs on staging

**Comment by LukSteib** [comment]
Assuming that I am checking the correct pod, it seems that the bot is not active. Logs: 

```
> auction-bot@1.0.0 start
> nuxt start
ℹ Listening on: http://192.168.40.65:3001/
 ERROR  Required RPC_URL env variable was not provided, please refer to the readme
  at start (src/index.ts:31:11)
  at src/index.ts:43:1
  at Resolver.g [as _require] (node_modules/jiti/dist/jiti.js:1:55111)
  at Resolver.requireModule (node_modules/@nuxt/core/dist/core.js:381:29)
  at Server._requireMiddleware (node_modules/@nuxt/server/dist/server.js:836:39)
  at Server._normalizeMiddleware (node_modules/@nuxt/server/dist/server.js:783:25)
  at Server.resolveMiddleware (node_modules/@nuxt/server/dist/server.js:856:23)
  at Server.useMiddleware (node_modules/@nuxt/server/dist/server.js:885:36)
  at Server.setupMiddleware (node_modules/@nuxt/server/dist/server.js:715:12)
  at async Server.ready (node_modules/@nuxt/server/dist/server.js:640:5)
```

**Comment by valiafetisov** [comment]
As specified in the #330, the variables are correctly set in the following secret paths:
```
secret read auction-ui/localhost/bot RPC_URL
secret read auction-ui/main.auction-ui.k8s.sidestream.tech/bot RPC_URL
secret read auction-ui/production.auction-ui.k8s.sidestream.tech/bot RPC_URL
secret read auction-ui/unified-auctions.makerdao.com/bot RPC_URL
secret read auction-ui/auctions.makerdao.network/bot RPC_URL
```

**Comment by LukSteib** [comment]
> As specified in the https://github.com/sidestream-tech/unified-auctions-ui/pull/330, the variables are correctly set 

Yep agree. @deusavalon any idea why secrets are not propagated correctly?

**Comment by deusavalon** [comment]
Everything does look fine, indeed :/ Hes definitly using the correct image not sure yet why he cant find the env var

**Comment by deusavalon** [comment]
The issue was that the current pipeline does not update the [secretChamberPath](https://github.com/sidestream-tech/unified-auctions-ui/blob/948f56f8af844403aadd0f50f26b8ecf957ea783/kubernetes/helm/templates/aws-chamber-read-secret.yaml#L12) in the kubernetes secrets. Therefor the value from the [values-files](https://github.com/sidestream-tech/unified-auctions-ui/blob/948f56f8af844403aadd0f50f26b8ecf957ea783/kubernetes/helm/values.override_main.auction-ui.k8s.sidestream.tech.yaml#L13) is never being written to the Secret linked above. To hotfix that @LukSteib and I changed the secretChamberPath in the secrets directly in the Kubernetes Cluster. This wont be needed everytime as the pipeline does for some reason not touch the secrets ... :D I will look out for a permanent solution and see whats going wrong but as long as the `secretChamberPath` is not being changed everything will work fine.

**Comment by LukSteib** [comment]
Can confirm now that bot logs are looking good.
Will proceed with prod deployment

Any objections from your side @valiafetisov ?

**Comment by LukSteib** [comment]
Moved forward and trigger the release. See release images: 
https://github.com/sidestream-tech/unified-auctions-ui/releases/tag/v1.5.0

**Comment by LukSteib** [comment]
- Frontend is locking good -> tests on `goerli` successful
- bot logs looking good:
```
> auction-bot@1.0.0 start
> nuxt start
ℹ Listening on: http://192.168.220.89:3001/
 WARN  collateral whitelisting: skipping setup due to missing WHITELISTED_COLLATERALS
 WARN  keeper: KEEPER_WALLET_PRIVATE_KEY variable is not set, keeper will not run
ℹ auctions: found "0" auctions () on "mainnet" network
ℹ auctions: found "0" auctions () on "mainnet" network
ℹ auctions: found "0" auctions () on "mainnet" network
ℹ auctions: found "0" auctions () on "mainnet" network
ℹ auctions: found "0" auctions () on "mainnet" network
ℹ auctions: found "0" auctions () on "mainnet" network
ℹ auctions: found "0" auctions () on "mainnet" network
ℹ auctions: found "0" auctions () on "mainnet" network
ℹ auctions: found "0" auctions () on "mainnet" network
ℹ auctions: found "0" auctions () on "mainnet" network
```
