### ISSUE TITLE
Discuss limitations of Dai.js

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#34]
### Goal
An overview of the current dai.js limitations

### Context
After facing unexpected drawback in the issue https://github.com/sidestream-tech/unified-auctions-ui/issues/31 where we discovered that passing the contracts to dai.js `addressOverrides` only replaces old addresses, but doesn't let us add new ones, we want to figure out what's the way forward.

### Tasks
- [x] Outline limitations / drawbacks
- [x] Outline potential solutions
- [x] Discuss
- [x] Conclude

**Comment by valiafetisov** [comment]
Limitations / drawbacks:
- Collateral-related issues:
  - dai.js does not allow dynamically adding (or removing) supported collateral types (even so it's possible to provide `addressOverrides` to the init function, it will only overwrite existing hardcoded collateral addresses)
  - Supported collaterals are hardcoded across several dai.js plugins (according to [the commit](https://github.com/makerdao/dai.js/commit/1328fc42b7152297372f53f6e19254f7af132b04) that adds support for MATIC and WSTETH, changes were made to `/dai-plugin-mcd/contracts/abiMap.js`, `/dai-plugin-mcd/contracts/addresses/*.json`, `/dai-plugin-mcd/src/tokens.ts`, besides `dai-plugin-liquidations` itself)
- General limitations
  - When gas limit computation fails it does not throw the error, but fallback to a very high hardcoded number
  - Gas price is taken from a free api which sometimes return error code, it is always taken from the mainnet
  - Gas limit computation is only done when the transaction is executed, so it's not possible to "precompute" it to display in the UI
  - Transaction tracking is cumbersome and doesn't work for transactions defined outside dai.js (eg auction reset)
  - dai.js does not have package-lock.json committed into any of the packages, therefore builds are not reproducible 
  - Since dai.js files were refactored to `ts`, typescript compilation fails (supposedly until all type errors are ignored)
  - There are a lot of hardcoded secrets throughout the code / tests

**Comment by benediktkaiser** [comment]
I also have the issue that I cannot deploy an edited version of DaiJS on my computer, meaning that I am not able to publish edits we may need to make.

Otherwise I think you perfectly summed up the problems we have been able to identify. :D

**Comment by valiafetisov** [comment]
> I cannot deploy an edited version of DaiJS on my computer

I suppose it's because of the `After dai.js switch to ts, typescript compilation fails` 🙂

**Comment by valiafetisov** [comment]
#### What we want:

Painless collateral onboarding. Ideally, we want to only modify one config file in order to add or remove supported collaterals and modify another config file in order to add or remove supported callees. Full list of contract addresses is already fetched directly from the chainlog.

#### Potential solutions:

1. Modify dai.js source code (requires upstreaming changes to the dai.js origin)
    1. Modify `dai-plugin-migrations`, `dai-plugin-mcd` plugins directly
    2. Extend/repair dai.js capability to add new collaterals via providing their addresses
    3. Replace some liquidations plugin logic so it doesn't use `smartContract` service, but take contract address directly as an argument
2. Patch dai.js in memory – find a place in memory (eg, inside `maker` singleton) where the list of contracts are stored and overwrite it directly in our code
3. Recreate dai.js liquidation-plugin functionality in our code

#### Considerations:

While `1` is the most straight forward goal, given general limitations it will be hard to align dai.js to our needs, since: all changes will require external reviews; all changes will need to support legacy systems to some extent, since not only us will be using dai.js; some things are just not part of the dai.js design (eg subscription pattern).
Then `2` is only a viable option in the short-term, since it's more of a quick hack than a proper solution. I am not even sure if it's possible.
Lastly, `3` is doable (`action-demo-keeper` actually doesn't depend on dai.js), but require reimplementing several key components:

-   Auction-related logic (can be copied over from the `LiquidationService`)
    -   Fetching of the auctions
    -   Authorisation, execution
-   Wallet connection (as `maker.addAccount`, transaction execution)
-   Fee estimation (gas prices, gas limits)
-   Transaction tracking

Possible splitting of this big change is if we would first change how we fetch and cache auctions (via events) to move it server-side in #33 and then do the rest of the refactoring. Or the other way around: we can still fetch auctions using dai.js, but do auth and execution the new way (although that would be a pure refactoring PR which doesn't add new functionality or possibility to fetch new collateral types). The only downside of moving away from dai.js is that some critical parts of it actually have automated tests.

Based on the above, I suggest to move away from dai.js in 3 steps:

1. Remove dai.js dependency for wallet connection, fee estimation, authorisation and execution (most of what we need is done in [`auction-demo-keeper/src/transact.js`](https://github.com/makerdao/auction-demo-keeper/blob/main/src/transact.js) file)
2. Remove dai.js dependency for auction fetching (all of which is done in [`dai-plugin-liquidations/src/LiquidationService.ts`](https://github.com/makerdao/dai.js/blob/dev/packages/dai-plugin-liquidations/src/LiquidationService.ts)), support new ERC20 collaterals
3. Introduce tests for the critical functionality: fetching, authorisation and execution

**Comment by LukSteib** [comment]
Thanks for this detailed write-up! 

One clarification question: 
> Recreate dai.js liquidation-plugin functionality in our code

* From previous discussions I understood that the whole library has interdependent service (ie. liquidation-plugin alone is not enough). Is that what you refer to when mentioning the "several key components" that would need to be re-implemented other than the auction-related logic (e.g. fee estimation?)

> Introduce tests for the critical functionality: fetching, authorisation and execution

* For this last step can we borrow from test logic that was introduced in dai.js or is this something that we will have to come up ourselves from scratch? 

---

* In general: We only overcome the collateral-related issues (mentioned [here](https://github.com/sidestream-tech/unified-auctions-ui/issues/34#issuecomment-1015225432) once all of the three mentioned steps to move away from dai.js are completed, right? Or is there a way to achieve this earlier?

**Comment by valiafetisov** [comment]
> From previous discussions I understood that the whole library has interdependent service (ie. liquidation-plugin alone is not enough). Is that what you refer to when mentioning the "several key components"

No, the interdependency is outlined here:

>> Supported collaterals are hardcoded across several dai.js plugins (according to the commit that adds support for MATIC and WSTETH, changes were made to /dai-plugin-mcd/contracts/abiMap.js, /dai-plugin-mcd/contracts/addresses/*.json, /dai-plugin-mcd/src/tokens.ts, besides dai-plugin-liquidations itself)

> For this last step can we borrow from test logic that was introduced in dai.js or is this something that we will have to come up ourselves from scratch?

We will of course "get inspired", so to say, from the existing tests, but the main work in this issue would be to set up testchain-based testing environment.

> Or is there a way to achieve this earlier?

We will overcome collateral-related issues, as well as most of the general limitations after 2 steps. Third step (automated testing) is required since we don't want to lose the overall stability of the code while overcoming limitations.

**Comment by LukSteib** [comment]
Ok thanks for clarification. 

Based on the comments up until this point I agree to your suggestion following the 3 step approach to move away from `dai.js`
