### ISSUE TITLE
Discuss switching between auction pages

### ISSUE THREAD

**Issue by zoey-kaiser** [sidestream-tech/unified-auctions-ui#357]
### Goal
We recently noticed, that there is no dedicated link to go back to either the unified page or the other auction page from either the dashboard, collateral auction or surplus auction page. This discussion hopes to find a solution to this issue.

### Context
I purpose two solutions:

- Add a back button to the top right of each page that lets one navigate back to the unified page, from which the user can select a new option. (See image below)
  - Pro: The user is much more aware of where to click to get back to the unified page
  - Con: It moves the logo a bit to the right, which may interrupt the flow of our page
- Make the logo on the top right navigate the user back to the unified auctions page.
  - Pro: It does not interrupt the flow of our page
  - Con: Some users may not make the connection, that the logo brings them back to the other page

Taking both options into consideration, I definitely prefer option 2.

![Screenshot 2022-07-18 at 10 30 04](https://user-images.githubusercontent.com/30908158/179473266-65453f22-c2f4-4207-b4b8-6371d7fc2912.png)

**Comment by LukSteib** [comment]
> Where,clicking on Maker or on the logo will redirect users back to the unified page. Clicking on Collateral auctions will redirect users to the table with auctions (and will keep the network). And, optionally, hovering Collateral auctions might bring other auction types that are supported.

I like the proposal for desktop view as it stands. 

> Probably something like: e) clicking logo will redirect users to the unified page and that's it f) clicking brings menu with 3 links: `Maker Auction Services`, `Collateral Auctions`, `Surplus Auctions`

Here I would vouch for option f). We might be able to re-use the modal for network selection and just provide the three options referenced above
