### ISSUE TITLE
Investigate debt auctions logic

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#361]
### Goal

Get understanding how different are `flop` auctions from the `flap`

### Context

For the planning and implementation of the debt auctions support, we want to investigate how they work and how difficult it will be to support them given our codebase and existing support of the surplus auctions. Same issue should investigate testing scenarios.

### Assets
- The contract https://github.com/makerdao/dss/blob/master/src/flop.sol
- Current UI portal https://auctions.makerdao.com/flop
  - Its source code https://github.com/makerdao/auctions-ui
- Python-based keeper that supports `flop` auctions https://github.com/makerdao/auction-keeper
- example investigation (as reference): https://github.com/sidestream-tech/unified-auctions-ui/issues/188#issuecomment-1148443724
- example implementation proposal (as reference): https://github.com/sidestream-tech/unified-auctions-ui/issues/188#issuecomment-1152161469

### Tasks

- [x] Outline investigation results

**Comment by KirillDogadin-std** [comment]
## FLOP debt auctions [[Auctions UI]]

- same bid parameters 

```
// --- Data ---

struct Bid {

uint256 bid; // gems paid [wad]

uint256 lot; // dai in return for bid [rad]

address guy; // high bidder

uint48 tic; // bid expiry time [unix epoch time]

uint48 end; // auction expiry time [unix epoch time]

}
```
- same structure for tracking the number of auctions: kicks counter is incremented when the auction is started; `Kick` event is emitted; auctions are stored in global state up until collection moment - then the auction is removed from the state.
- Difference:
	- Kick event of the flop/debt contains the additional paremeter `address indexed gal`. This is the parameter that defines who will be the receiver of the lot: "highest bidder" when the auction is started.

### FLOP auction flow:
1. Auction is started via calling `kick` with the following params:
	1. address of the initial high bidder,
	2. how much MKR will winner receive (`lot`)
	3. how much is the initial bid `bid`
2. To bet on the auction one has to call `dent` and the following conditions have to be met:
	1. Flopper contract is online
	2. the high bidder has to be defined (read: auction exists)
	3. the auction has to be not finished (`tic` auction parameter has to be greater than current time `now`)
	4. auction has to be not expired: `end` parameter hat to be greater than `now` current time.
	5. bid (amount of DAI bet on the auction) has to be of exact value as the one auction has.
	6. The amount of MKR acquired has to be less than the one auctioned
	7. the amount of MKR acquired has to be at least 5% less than the currently auctioned amount
3. the finishing time of the auction is increased.
4. the new bid is placed: the VAT balance of the bidder is decreased, the balance of the previous bidder is refunded.
5. when the time expires, one can call `deal` to receive the DAI in exchange for the MKR:
	1. auction has to be either expired or finished
	2. the MKR is `mint`ed to the winner's address: now they have it in VAT
6. when the transfer to the VAT of the winner is made, the auction's data is deleted.
7. If the auction is expired and there's no winner, one can restart it;
	1. it has to be expired
	2. it has to have no bets (no finishing point)
	3. The amount of mkr recveived (starting value) will be increased. As of now by 50%

### The user of the auction is thus has to: 
  - provide VAT with dai allowance
  - authorize DAI for wallet transactions

**Comment by LukSteib** [comment]
> Kick event of the flop/debt contains the additional paremeter `address indexed gal`

What is the difference to the `guy` in this case?

> bid (amount of DAI bet on the auction) has to be of exact value as the one auction has.
> The amount of MKR acquired has to be less than the one auctioned

Do you share the following understanding for this auction type:
* `bid` always stays the same for an active auction (read: If the auction is started with a `bid` of 50000 DAI it always stays like that)
   * the `bid` amount is specified via [`vow.sump`](https://etherscan.io/address/0xa950524441892a31ebddf91d3ceefa04bf454466#readContract)
* bidders specify a reduced `lot` they are willing to receive for paying the fixed `bid` 
  * this new `lot` has to be at least the prev `lot` lowered by `beg` 
* This time Dai (higher than or equal to `bid`)  needs to be deposited to the VAT before being able to call the `dent` function
* The winner received `MKR` in the VAT and has to withdraw it from there

**Comment by KirillDogadin-std** [comment]
> What is the difference to the guy in this case?

Initially the auction is initialized to point to the VAT as the highest bidder.

This leads:
  - the very first actual bidder puts the bet into the vat

> Do you share the following understanding for this auction type:

Yes. except for

>The winner receives MKR in the VAT and has to withdraw it from there

because it seems to me like the mkr just arrives into the wallet.

**Comment by valiafetisov** [comment]
>  To bet on the auction
> the bet into the vat

As pointed out previously, let's _never_ use verb `bet` in our discussions and in the codebase as they are not interchangeable with the verb `bid`. Refer to the dictionary :

https://dictionary.cambridge.org/dictionary/english/bet
https://dictionary.cambridge.org/dictionary/english/bid

> https://github.com/sidestream-tech/unified-auctions-ui/issues/361#issuecomment-1201003078

Can you please outline not what is the same, but only what is different compared to the flap auction type? 
It would also help to link the exact places in the contracts which are different.

**Comment by KirillDogadin-std** [comment]
>  let's never use verb bet 

adjusted the comments

## Differences:

1. Namings of bidding methods (now it's `dent` and not `tend`)
2. Different initialization, here the kick event has additional parameter of an address of "highest bidder". Effectively that has no impact on our tool because this is related to the bidding logic which manages the dai.
3. different approach of how the bid is handled: here it is VAT and not MKR, it has to be present in VAT
  4. as outlided by @LukSteib above, one has to pay the fixed amount of mkr in exchange for MKR. Each bidder specifies the acceptible amount of MKR they're willing to receive for the known amound of DAI. Each consequent bidder thus has to submit a bid with lower number than the previous bidder. 
5. Consequently (see 3), the permission set is different. The functionality for granting permissions is already present in our tool though: one needs VAT allowance and due to that DAI transaction authorization as well if i understand correctly.

**Comment by valiafetisov** [comment]
Thanks!

> one has to pay the fixed amount of DAI in exchange for varying amount of MKR

Is this fixed amount hardcoded in the contract (ie known in advance) and/or emitted during the kick?

> Each consequent bidder thus has to submit a bid with lower number than the previous bidder.

Is there a minimum distance between bids like `flap` bids should have or is the difference can be as little as one digit? If not, is the formula differs from the formula determining next bid in flap auctions? Is it computed based on a different value taken from the contract or the same one?

**Comment by KirillDogadin-std** [comment]
> Is this fixed amount hardcoded in the contract (ie known in advance) and/or emitted during the kick?

it is emitted via kick

> Is there a minimum distance between bids

yes

> formula

`newBet * 1.05 <= previousBet`

**Comment by valiafetisov** [comment]
Looking at the code, `1.05` is not a hardcoded, but a [public variable](https://github.com/makerdao/dss/blob/fa4f6630afb0624d04a003e920b0d71a00331d98/src/flop.sol#L74). On the currently live contract [it is set](https://etherscan.io/address/0xa41b6ef151e06da0e34b009b86e828308986736d#readContract) to `1.03`.

Also, after the flyover, reset functionality seems different to me, since it [changes the amount of auctioned DAI](https://github.com/makerdao/dss/blob/fa4f6630afb0624d04a003e920b0d71a00331d98/src/flop.sol#L134) by `pad`. Right?

**Comment by KirillDogadin-std** [comment]
> Looking at the code, 1.05 is not a hardcoded, but 

Oops, sorry, I for some reason interpreted the q to be related to the amount of DAI paid

> Reset

Correct, the alteration logic of the auction differs as well, although from the interface perspective the call is analogous. I'll add the point into the summary

**Comment by valiafetisov** [comment]
>> Is this fixed amount hardcoded in the contract (ie known in advance) and/or emitted during the kick?
>
> it is emitted via kick

It is emitted via the kick, but also seems to be known in advance: 
https://github.com/makerdao/dss/blob/fa4f6630afb0624d04a003e920b0d71a00331d98/src/vow.sol#L66-L67

> q to be related to the amount of DAI paid

Yes, that question was related to the question about the `lot`. But `1.05` that you brought up was not a sufficient answer about the minimum (or rather maximum) next bid.

> increasing by 50%

Please be more specific in the description, since I just pointed out that those numbers are not hardcoded and need to be fetched from the contract. The summary of the `differences` suppose to explain that some additional information (at least `beg`, maybe also `pad` for explanation text) needs to be fetched.

> kick event has additional parameter of an address of "highest bidder"

Kick event is only emitted at auction start. `gal` is then effectively the address of the wallet who kicked the auction. 

The other difference I see is that initial kick even receives a non-zero bid. According to that line https://github.com/makerdao/dss/blob/fa4f6630afb0624d04a003e920b0d71a00331d98/src/vow.sol#L145. That means that although the auction is just started, we might already know dai/mkr price.

After this is done, I suppose that new issue should be created for implementing missing methods and making store-based interface to them.

**Comment by valiafetisov** [comment]
> i fail to see the use case for now

It seems like you try to do two things at once: 1) investigate the difference and 2) judge its applicability to us. I think it's hard to do it in general, but also makes it impossible to review.

> the logic of the price step is essenetially the same

For me it seems like the step logic is reverse. Users have to put lower bids, not higher ones. That is a significant difference that have to be reflected not only in the explanatory text, but also in the way bidding work on the frontend, the way `nextHighestBid` is calculated and called. It's definitely worth mentioning in the difference section as the key distinction.

> The `gal` address being the same as the address of the kicker is analogous/extremely to the flap, is it not?

Yes, it's similar to the flap, with the difference that the address is a) passed as an argument b) emitted together with `Kick`

**Comment by KirillDogadin-std** [comment]
> It seems like you try to do two things at once: 1) investigate the difference and 2) judge its applicability to us. I think it's hard to do it in general, but also makes it impossible to review.

added as (8) in the differences.

>  It's definitely worth mentioning in the difference section as the key distinction.

It already is as (3)
