### ISSUE TITLE
Fix known wallet related problems

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#367]
### Goal
Improve overall wallet connection experience by fixing known issues

### Context
Recently we've encountered the following three problems that need to be addressed with this issue:
~1) Switching between accounts from within metamask modal is not reflected by the indicated wallet address in the header of our UI~
2) Disconnect connected wallet via button in header doesn't work
3) The auth states for the connected wallet are not properly fetched (While auth to withdraw DAI from VAT via wallet popup was given and correctly indicated when on `/collateral` page, the same step is indicated as requiring authorisation when on `/surplus` page.)

### Tasks
- [x] Fix problem 1)
- [x] Fix problem 2)
- [ ] Fix problem 3)

### Assets:
2)
https://www.loom.com/share/32fa7d678fa246ec9edebeda67dfa399

3)
unauth:
<img width="900" alt="image" src="https://user-images.githubusercontent.com/36229155/179964509-add5eb3d-ae87-4ef7-8825-8542a3ec12f4.png">

auth (same wallet)
<img width="900" alt="image" src="https://user-images.githubusercontent.com/36229155/179964661-847b8ff2-7670-4eb3-83ff-b2812feac58b.png">

**Comment by LukSteib** [comment]
> Switching between accounts from within metamask modal is not reflected by the indicated wallet address in the header of our UI

Not able to reproduce this behaviour. Checked on production and it looks good. I am able to switch between different connect accounts from within metamask and the changes are properly reflected in the UI (e.g. by showing the correct address in header). Did you experience this problem on another environment (@zoey-kaiser , @valiafetisov )

**Comment by valiafetisov** [comment]
> Not able to reproduce this behaviour

Not able to reproduce it either. Also on staging

**Comment by LukSteib** [comment]
> Not able to reproduce it either. Also on staging

Updated issue accordingly
