### ISSUE TITLE
Create debt auction mock

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#392]
### Goal
Create mock for UI flow of debt auctions

### Context
debt auctions is the third auction type to be integrated in our UI. As always mock should be used to get an understanding and agreement on the planned UX flow.
In this case we also want to use the mock to check what to components to copy over from surplus auctions

### Tasks
- [x] Create Mock
- [x] Discuss 
- [x] Create outline of what needs to be done

**Comment by LukSteib** [comment]
See Mock: https://whimsical.com/makerdao-debt-TLjy6A3d3hV7XphhayiXq

<details><summary>MOCK v1</summary>
<p>

![MakerDAO debt@2x](https://user-images.githubusercontent.com/36229155/182543058-dfb27320-3df8-4ede-97e3-715579fd71e7.png)


</p>
</details>

**Comment by LukSteib** [comment]
- Create basic debt auction page
    - adjust header, extend new navigation modal, adjust landingblock, adjust texts
- Create `DebtAuctionsTable`
    - Copy `SurplusAuctionsTable`
    - to be adjusted columns
        - "Auction amount" -> "Bid amount"
        - "Highest bid" -> "Lowest auction amount"
    - to be adjusted auction states
        - "Collect DAI" -> "Collect MKR"
- Create `DebtAuction` page
    - Copy `SurplusAuction`
    - to be changed table rows
        - "Highest Bid" -> "Bid"
        - "Auction Amount" -> "Auction amount to receive”
        - Change text
        - change button copy
- Create `DebtAuctionRestartPanel`
    - Use `AuctionRestartPanel` and use the `Surplus Auction` version -> no need to change anything
- Create `DebtAuctionBidTransactionTable`
    - Copy `SurplusAuctionBidTransactionTable`
    - to be adjusted rows
        - "Auction Amount" -> "Bid"
        - "Current Highest Bid" -> "Current amount to receive"
        - "Lowest Next Bid" -> "Highest next amount to receive"
        - "The Amount to bid" -> "The amount to receive" (ie. input field)
        - in general: price denotation should be DAI per MKR wherever we currently have MKR per DAI
- Use existing `WalletConnectionCheckPanel`
- Create `WalletdDaiDepositCheckPanel`
    - Take over https://github.com/sidestream-tech/unified-auctions-ui/pull/314 and adapt it in a way to change MKR for DAI
- Use existing `WalletAuthorizationCheckPanel`
- Create `WinningBidCheckPanel`
    - Copy `HighestBidCheckPanel`
        - Adjust the status messages
        - Adjust the text
        - Adjust the indicator of the current lowest amount to receive
        - Adjust the button copy
- Create ``CollectDebtAuctionPanel``
    - Copy `CollectSurplusAuctionPanel`
        - Change DAI to MKR
        - Change button

**Comment by valiafetisov** [comment]
I think auction table is very confusing this way. Especially this part:

<img width="429" alt="Screenshot 2022-08-03 at 13 38 29" src="https://user-images.githubusercontent.com/3393626/182576894-fd529325-9daa-4f7a-9d2b-b54c6a83ddba.png">

I would at least:

- Call `Bid` field as `Fixed bid` or `Auction fixed bid` (to indicate the although it's called bid it can't be changed)
- Call `Current amount to receive` as `Current compensation`
- Call `Highest next amount to receive` as `Next lowest compensation`
- Call `You're not the bidder with lowest amount to receive` as `You're not the latest bidder`
- Call `The amount to receive` as `Desired compensation`?

**Comment by LukSteib** [comment]
> Call `Highest next amount` to receive as `Next lowest compensation`

The `next lowest compensation` might also be confusing. Because in theory a user could directly place a bid accepting a way lower compensation than the next lower (ie. `lot` - (`lot` * `beg`)) one. Say accepting a compensation of 50 MKR instead of 240 MKR, which would be the next lower on. 
So my proposal here to potentially go with `Next lower compensation` instead of `lowest`.

**Comment by LukSteib** [comment]
Adjusted the Mock based on the comments:

<details><summary>MOCK v2</summary>
<p>

<img src=https://user-images.githubusercontent.com/36229155/183025416-b212d7be-d4da-4a76-931b-6da8bdf41a94.png width=600>

</p>
</details>

**Comment by LukSteib** [comment]
Current task overview:

- Create basic debt auction page
    - adjust header, extend new navigation modal, adjust landingblock, adjust texts
- Create `DebtAuctionsTable`
    - Copy `SurplusAuctionsTable`
    - to be adjusted columns
        - "Auction amount" -> "Bid amount"
        - "Highest bid" -> "Lowest auction amount"
    - to be adjusted auction states
        - "Collect DAI" -> "Collect MKR"
- Create `DebtAuction` page #395 
    - Copy `SurplusAuction`
    - adjust where needed 
- Create `DebtAuctionRestartPanel`
    - Use `AuctionRestartPanel` and use the `Surplus Auction` version -> no need to change anything
- Create `DebtAuctionBidTransactionTable`
    - Copy `SurplusAuctionBidTransactionTable`
    - Adjust where needed
- Use existing `WalletConnectionCheckPanel`
- Create `WalletdDaiDepositCheckPanel` #393 
    - Take over https://github.com/sidestream-tech/unified-auctions-ui/pull/314 and adapt it in a way to change MKR for DAI
- Use existing `WalletAuthorizationCheckPanel`
- Create `BidCheckPanel`
    - Copy `HighestBidCheckPanel`
        - Adjust the status messages
        - Adjust the text
        - Adjust the indicator of the current lowest amount to receive
        - Adjust the button copy
- Create ``CollectDebtAuctionPanel``
    - Copy `CollectSurplusAuctionPanel`
        - Change DAI to MKR
        - Change button
- Implement `DebtFlow`
- Implement `DebtAuctionsContainer`

**Comment by valiafetisov** [comment]
> Would we already be able to a) show fix bid amount

Yes, according to investigation, the MKR amount to receive is set to some specific number at the `kick` (compared to the surplus auction where it's set to 0). Based on this, `No amount set yet` state in the table should also not exist and just be `unknown`.

> `Next highest compensation`

You're right, that sounds better.
