### ISSUE TITLE
Extend the Keeper to bid on Surplus Auctions

### ISSUE THREAD

**Issue by zoey-kaiser** [sidestream-tech/unified-auctions-ui#415]
### Goal
Our current implementation of the keeper only works with Collateral Auctions. This PR aims to incorporate the Surplus Auctions into the flow as well. 

### Context
The current keeper implementation has two main ingress points. The first is a function called [`setupKeeper`](https://github.com/sidestream-tech/unified-auctions-ui/blob/main/bot/src/keeper.ts#L10), which runs once when the bot is started. Inside the function we do the following steps:
- Check if the user set a `WALLET_PRIVATE_KEY`
- Setup the Signer (wallet with perms to execute transactions)
- Verify the wallet works
- Check the `KEEPER_MINIMUM_NET_PROFIT_DAI`

You might have to either modify the `KEEPER_MINIMUM_NET_PROFIT_DAI` or add a second variable for Surplus Auctions, as we do want to give the user the option to define how much profit they want to make. 
This initial Setup Keeper function can stay as it is. When you try to execute Surplus Auctions, you will be able to use the same signer, defined here.

The second ingress point is the [`participate`](https://github.com/sidestream-tech/unified-auctions-ui/blob/main/bot/src/keeper.ts#L131) function. I will be going into less detail here, as every auction type has a different bidding flow, meaning that you will not be able to copy the logic from here. However I would recommend moving this function into a new file (called `collateralKeeper` for example) and renaming the function to `participateInCollateralAuctions`. 

In order to introduce the bidding on SurplusAuctions, you will need to use the function [`bidToSurplusAuction`](https://github.com/sidestream-tech/unified-auctions-ui/blob/main/core/src/surplus.ts#L143), however there are some caveats here we need to examine! Before I get into them exactly, I will provide a rough outline of what the participate function would need to look like:

```js
export const participateInSurplusAuction (surplusAuction: SurplusAuction) {
  // check if setupKeeper hasn't run
  if (!isSetupCompleted) {
    return;
  }

  const signer = await getSigner(network);

  // Check the SurplusAuction State, to ensure you can actually bid on it

  // enrich the SurplusAuction into a SurplusAuctionTransaction

  // check the end auction profit (combine end profit and fees to see if it is profitable)

  // ensure the auction clear profit (without transaction fees) meets the set requirements

  // ensure the wallet has enough MKR allowance to bid on the auction

  // if the allowance is not enough, set it to unlimited or to the amount needed (up to you)

  // bid on the auction
}
```
Whenever you complete one of the checks (say allowance check) and set new values, be sure to re run the participate script!

Now some more explanations:

Firstly, you will need to enrich the `SurplusAuction` to a `SurplusAuctionTransaction`. You can use the [enrich function](https://github.com/sidestream-tech/unified-auctions-ui/blob/main/core/src/surplus.ts#L204) for this. The information we gain from this enrichment is important as we need to...

- Know the next minimum bid
- Add any Transaction fees
- Check if the net profit is still high enough to cover the `KEEPER_MINIMUM_NET_PROFIT_DAI`

Extra: If you want to, you can also write a second function that collects the `ready-for-collection` auctions, that were won by the keepers wallet. When you do the auction state check, you can see if the auction is ready for collection. If it is, return the participate function and call your new function. You can retrieve the keeper wallet address by running: 

```js
const signer = await getSigner(network);
const address = await signer.getAddress();
```

**Comment by LukSteib** [comment]
To prevent confusion, since we are referring to surplus auctions here: 

>   // ensure the wallet has enough DAI in VAT to complete the transaction

This step is not needed as bidding on a surplus auction is done with `MKR` and directly from the wallet and not via VAT. So it rather needs to be checked that wallet has enough `MKR` to place the desired bid.

>   // ensure the wallet has enough allowance to bid on the auction

This reference to the MKR allowance

**Comment by zoey-kaiser** [comment]
> To prevent confusion, since we are referring to surplus auctions here:
> 
> > // ensure the wallet has enough DAI in VAT to complete the transaction
> 
> This step is not needed as bidding on a surplus auction is done with `MKR` and directly from the wallet and not via VAT. So it rather needs to be checked that wallet has enough `MKR` to place the desired bid.
> 
> > // ensure the wallet has enough allowance to bid on the auction
> 
> This reference to the MKR allowance

My bad! I adjusted the mock. I have been working so much on the Debt Auctions, that I mixed them up 😓
