### ISSUE TITLE
Improve hardhat setup

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#420]
### Goal

Make running local testing environment more developer-friendly 

### Context

After merging https://github.com/sidestream-tech/unified-auctions-ui/pull/408, we would have at least 2 main scenarios for testing, but actually more (if counting surplus auctions on the previous contract). Therefore, we would like to have a setup where:

1. From one side it's very easy to run local testing environment via interactive cli. The developer should be able to navigate to the `hardhat` folder (or maybe we abandon it and use `core` folder for that) and execute single command which will:
    - check env vars
    - show list of available simulations (eg: `3 WSTETH-A auctions`, `Single debt auction`, etc)
2. From the other side make adding new simulations an easy task via extensible config (stored directly in our codebase) where developer can specify
    - Name of the simulation
    - Optional block number
    - Function that needs to be executed
    - etc

For inspiration, please have a look at the [`choose.ts`](https://github.com/sidestream-tech/unified-auctions-ui/blob/main/chaos-proxy/src/choose.ts) and the use of `prompts` in that folder.

### Tasks

- [ ] Propose config structure, refactoring scope
- [ ] Implement

**Comment by KirillDogadin-std** [comment]
- move all simulation logic from `core/helpers` into `core/simulation`
- add the `configurations.json` to the simulation folder. 
- add the `core/simulatoin/scripts` directory
  - `index.ts` exports all the simulation functions
  - each module exports one simulation function
- add `core/choose.ts` that utilises `promts` and leverages `core/simulation/scripts` module
  - have the `configurations.json` specify what will be prompted
  - promt the name of the function 
  - based on the response, promt the arguments
  - call `scripts[promptedScriptName](**promptedArgs)`

`configuration.json` looks like the following

```json
{
  "names": {
    "causeDebt": "Create debt auction"
  },
  "args": {
    "causeDebt": [
      {
        "type": "text",
        "name": "value",
        "message": "block number"
      }
    ]
  }
}

**Comment by valiafetisov** [comment]
> `configuration.json` 

Why do you want to store `names` and `args` in two different places in the json? So the developer adding new simulation can forget to add one or the other or that it can't be enforced via types? I also think that this file doesn't need to be `json` but can be `ts` to take advantage of our tooling.

```ts
const [
   {
      title: 'Create debt auction',
      entries: ['path/name of the test 1', 'path/name of the test 2'] // in case we want to run two different simulations (eg collateral + debt auctions running at the same time)
   }
]
```

> based on the response, promt the arguments

Do you mean there can be different arguments to the same function? Can you give an example of when/why is it useful?

> * move all simulation logic from `core/helpers` && `core/scripts` into `core/simulation`

How this will affect `hardhat` folder? Do we still actually need it then? Cause one of the main goals of this issue was to refactor `hardhat` setup where we currently hardcode some specific block number.

Can you also imagine this config structure being used to run with setup like here https://github.com/sidestream-tech/unified-auctions-ui/pull/404?

**Comment by KirillDogadin-std** [comment]
> Can you give an example of when/why is it useful?

Default paramterers can be configured, we dont lose anything from allowing to configure. And we never know what will be required from the simulation in the future and which `require` will have to pass simulatniously. By hardcoding the parameters we risk facing the case where the simulation goes through and disables some other functon (makes in not possible to call it).

> How this will affect hardhat folder? 

it does not.

> Do we still actually need it then?

it depends i guess on wether we want to intertwine the dependencies there.

- One way would be just to remove the hardhat package and transwer it all into the core + add the scripts as i proposed above.
- The other way is that we would have to put the scripts into the hardhat foler, but then we have to install hardhat in the core anyway so that the tests pass. Which means we still have to have hardhat and its config set up in the core = duplicated hardhat remains present.

**Comment by zoey-kaiser** [comment]
We recently had to test Surplus Auctions via Hardhat, due to the chaos proxy being down. 
I wanted to reference the block number we used, to ensure we don't lose it.

`14052140` is a block in which SurplusAuctions are available.

**Comment by valiafetisov** [comment]
> i suggest still something like

Can you please elaborate on why are you suggesting to use Record as a config structure? Why do you need to force devs to  come up with the extra `causeDebt`-like key and add it into two places?

> Default paramterers can be configured, we dont lose anything from allowing to configure. And we never know what will be required from the simulation in the future and which `require` will have to pass simulatniously. By hardcoding the parameters we risk facing the case where the simulation goes through and disables some other functon (makes in not possible to call it).

Can you please give a specific example (eg an example of the config that takes advantage of this)? I still can't see a valid use-case for it. 

> - One way would be just to remove the hardhat package and transwer it all into the core + add the scripts as i proposed above.
> - The other way is that we would have to put the scripts into the hardhat foler, but then we have to install hardhat in the core anyway so that the tests pass. Which means we still have to have hardhat and its config set up in the core = duplicated hardhat remains present.

So what is the proposal? I suggest to look at it from the perspective of the user who wants to run a simulation. Where do they have to go (read `cd`) and how many commands do they have to call. Does it makes sense? Eg, "in order to start a simulation please `cd` into the `/simulations` folder, run `npm install && npm run dev`" (effectively renaming `hardhat` to `simulations`) or "`cd` into the `/code` folder, run `npm install && npm run simulate`"?

**Comment by KirillDogadin-std** [comment]
> Can you please elaborate on why are you suggesting to use Record as a config structure? Why do you need to force devs to come up with the extra causeDebt-like key and add it into two places?

over here the `causeDebt` key of the record acts like a pointer to which function should be run so that the magic happens. The value of the record defines what questions the user will be asked

> Can you please give a specific example

```ts
{
                type: 'text',
                name: 'network',
                message: 'Network',
                initial: 'custom',
            },
            {
                type: 'text',
                name: 'debtAmountDai',
                message: 'Protocol Debt In Dai',
                initial: '10',
            },
            {
                type: 'text',
                name: 'mkrOnAuction',
                message: 'Initially sold MKR auction',
                initial: '1000',
            },
            {
                type: 'text',
                name: 'daiOnAuction',
                message: 'Dai requested by auction',
                initial: '1000',
            },
```

The simpliest case is having some other hardhat network name or willing to adjust the debt so that on a block number XXX we can actually be on the created auction. In the setup with the hardcoded values we would be forced to e.g. part take in the liquidation auctions to get some dai first.

> So what is the proposal?

- the proposal is to remove `hardhat` directory from the project, delegate the forking to `core` hardhat module.
- in order to run the simulations one would have to:
  - once run `npm i` in the `core` folder (so by default it is already done)
  - run `npm run hardhat` to boot up the fork.
  - run something like `npm run simulation` which under the hood just calls the script via `npx hardhat run` and use the prompt to choose the config.

> Also, do you think this code belongs to the core package

It's part of the core. the reason that i would suggest to place this in the core is because it's already tightly tied to hardhat due to the integration tests; the simulation (assuming they're running on the fork) would also be able to use core package functionality directly and the tests on their own would be able to also use the scripts that are running under the hood (e.g. `causeDebt`) as fixtures for setup-teardown.

**Comment by valiafetisov** [comment]
> The simpliest case is having some other hardhat network name or willing to adjust the debt

I see that it adds overhead into confirming default values every time you run a simulation without actual purpose. If we want to cover one other specific edge case, we would better add another simulation that executes it instead of providing/confirming values manually every time, but I don't see the edge case here. Why would you change the input parameters?

Instead, the more important feature that i see is: step-by-step execution of simulations. Currently, when the simulation is executed, it already reaches its final state (eg running auctions). Instead, we want to be able to execute it step by step. Most obvious example, that we will already use: the developer first starts (forked) RPC endpoint (eg first part of the execution), then connects frontend or the bot to the RPC and only then executes (another part of the) simulation. Use-case: working with state change: started auction tweets, auction that changes its state, finished auction, concurrent bidding, socket-based fetching of the events, etc.

And yes, regarding your comment during daily, it was implied but never documented as requirement that `npm install && npm run simulate` should run both hardhat fork and the selected simulation in one process.


```ts
const SIMULATIONS = [
   {
        title: 'Create debt auction',
        steps: [
            { 
                title: 'Reset blockchain',
                entry: 'path/name of the test 1',
            },
            { 
                title: 'Create debt auction',
                entry: 'path/name of the test 2',
            },
            { 
                title: 'Expire the auction',
                entry: 'path/name of the test 3',
            }
        ]
   },
   // ...
]
```

Execution log something like
```
$ npm run simulate

> Please select simulation type
- Debt auction
- Collateral auction WSTETH-A

Running "Debt auction" step "Reset blockchain"...
Logs printed from this step (eg block number)
> Press enter to proceed to the next step "Create debt auction"

Running "Debt auction" step "Create debt auction"...
One debt auction created with ID 1 and debt 50000 DAI
> Press enter to proceed to the next step "Expire the auction"

Running "Debt auction" step "Expire the auction"...
Done
> Press enter to quit the simulation and shut down RPC endpoint
```

**Comment by KirillDogadin-std** [comment]
Generally speaking with this description, i would say that the picture of what should we have on hands now is way clearer and from initial point made in the header comment i invisioned a different, a bit less abstract tool. I don't think there's major problems with doing it this way.

As to answer the specific question based on the my previous understanding of the requested feature behaviour

> Why would you change the input parameters?

in the proposed by you streamlined approach with single command it is making less sense to change the input parameters. But the flexible case with multiple simulations/actions that one has to run one by one (e.g. running some simulation that creates debt auctions and then run some simulation that changes the wallet balance) is more unpredictable and would require parametrization

**Comment by valiafetisov** [comment]
> the picture of what should we have on hands now is way clearer

Nice to hear that

> Then i would propose the following implementation plan:
> the function that runs the sequence of steps (provided as args)

Not sure if it makes sense to me, but I will comment what I understood:

> have one script per step e.g. in `steps` module

It doesn't actually have to be the actual script file, but can be a function, eg:
```ts
const SIMULATIONS = [
   {
        // ...
        steps: [
            { 
                title: 'Reset blockchain',
                entry: () => functionNameOne(123),
            },
            // ...
        ]
   },
   // ...
]
```

> the function that runs the sequence of steps

To be clear: in the proposed solution it only runs next step after the user input.

**Comment by KirillDogadin-std** [comment]
yes to all, we're aligned
