### ISSUE TITLE
Enable calling auth-protected methods for testing

### ISSUE THREAD

**Issue by KirillDogadin-std** [sidestream-tech/unified-auctions-ui#505]
### Goal

Set of functions that enables us to call auth-protected methods

### Context

Some collateral auctions simulations (such as `UNIV2DAIUSDC-A`, `WSTETH-B`) can't be currently performed due to some settings in the vault/liquidation-relevant contracts. To enable it we have to either directly edit those changes, enable us to call `file`-like administration methods or in other way provide us with ability to change them (eg compile, vote, execute the spell, like it's done the proper way).

### Assets

- Overview issue #501

### Tasks

- [x] Research who has administrator privileges, how to get them, report it here
- [x] Propose the implementation & discuss
- [x] Implement

**Comment by KirillDogadin-std** [comment]
It seems like the pr https://github.com/sidestream-tech/unified-auctions-ui/pull/506/files is already implementing *at least* part of the functionality that is relevant for this feature.

For being able to change the maker protocol parameters on the blockchain one has to acquire administraton power. For that one has to "win" the elections: the address has to be most voted among all other candidates. Later on this address will be able to adjust protocol configuration after the `lift` (https://docs.makerdao.com/smart-contract-modules/governance-module/chief-detailed-documentation#lift-address-whom) function will be called. If having won the election is enough to introduce any change to the protocol, then the setup from the mentioned pr can be reused in the simulations to adjust values via `lift`. Then after that the simulations that are fixed by `lift`ing values can be introduced in order to support more collaterals.. WIth the tooling from #506 this issue should be resolved fast enough

**Comment by valiafetisov** [comment]
> Research who has administrator privileges, how to get them, report it here

The easiest way, it seems, to just modify [`MCD_VAT.wards` mapping](https://github.com/makerdao/dss/blob/fa4f6630afb0624d04a003e920b0d71a00331d98/src/vat.sol#L28) to add our hardhat address, since [it's the only thing that guards those methods](https://github.com/makerdao/dss/blob/fa4f6630afb0624d04a003e920b0d71a00331d98/src/vat.sol#L31-L34). I suggest to add a specific function, eg `overwriteVatAuthorization(walletAddress = HARDHAT_PUBLIC_ADDRESS)` and create a of set functions like `setCollateralDebtCeiling(collateralType, amount = new BigNumber(MAX))`

**Comment by KirillDogadin-std** [comment]
By extension you're proposing to overwrite `wards` mapping in every contract we have to introduce change to, correct?

(Asking since we're in the need to overwrite also JUG as of #501 [solution summary](https://github.com/sidestream-tech/unified-auctions-ui/issues/501#issuecomment-1282146224).)

**Comment by KirillDogadin-std** [comment]
Discovered additional complexity with the JUG contract: it apparently requires to use `file` function within the same transaction as `drip` because the `file`ing of the stability fee accumulaton rate is only possible if [this](https://github.com/makerdao/dss/blob/17187f7d47be2f4c71d218785e1155474bbafe8a/src/jug.sol#L108) condition is fulfilled.
