### ISSUE TITLE
Adjust skip time step for collateral auction simulation

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#515]
### Goal
We ensure that the auction is in a profitable state but not expired yet after executing the "Skip Time" step of the current simulation

### Context
We already have a simulation in place that allows the creation + liquidation of vaults for all supported collateral types. This ultimately enables us to test auction participation.
However, in order to participate in an auction via swap feature it needs to be profitable (ie. enough time has be passed in order for the auction price to be below market price).

For some collateral auctions (explicitly `USDC-A` and `PAXUSD-A`) the auction is not yet profitable after the "Skip Time" step in our simulation.
Since we know when the auction will expire let's use this info and skip the time to a point in time that is closely before the auction expiration.

### Tasks

- [ ] Adjust the "Skip Time" step of the collateral auction simulation to increase likelihood of auction being profitable (and hence swapable)

**Comment by valiafetisov** [comment]
Technical suggestion: use "end auction date" value to figure out how far the auction needs to be warped + make sure a few blocks left before deadlines to do authorisations.
