### ISSUE TITLE
Fix unknown contract related simulation problem

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#518]
### Goal
Simulations that fork a block in the past still work

### Context
We encountered that some of the old simulations (e.g. forking a block at some point in the past where there was an active `WSTETH-A` auction) do no longer work. 
The error shows that it is due to the contract `MCD_CLIP_RETH_A` not being available. This is due to the fact that back in the days this contract simply did not exists yet as RETH was onboarded only lately.

### Assets

```sh
 ERROR  collateral loop error No contract address found for "MCD_CLIP_RETH_A"                                             18:53:10

  at _fetchContractAddressByNetwork (/Users/luksteib/Github/unified-auctions-ui/core/src/addresses.ts:32:11)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Tasks
- [ ] Fix the problem described above and make sure simulations work as expected

**Comment by KirillDogadin-std** [comment]
The error was occuring when one starts up bot with a specific configuration.

Rubberducking has revealed that it's enought to remove the RETH collateral from the whitelist for the bot to start up successfully.

Issue can be closed apparently. If anything is needed, readdress pls

**Comment by LukSteib** [comment]
My bad - thx for clarification.
