### ISSUE TITLE
Investigate gas error on goerli

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#526]
### Goal
Enable testing scenarios on goerli

### Context
Currently when trying to execute a tx on `goerli` this is prevented by a gas related error (see assets below for console output).
AFAIK we compute the `maxFeePerGas`[ by taking the `baseFeePerGas` times 2 ](https://github.com/sidestream-tech/unified-auctions-ui/blob/948f56f8af844403aadd0f50f26b8ecf957ea783/core/src/gas.ts#L32). So it makes me wonder how we can end up in a scenario like described in the error mesage where the `maxFeePerGas` is lower than the `baseFeePerGas`

### Assets
```
Transaction error: "err: max fee per gas less than block base fee: address 0x4f3B7fb6204C614B28F0e1f50Dc1C99175631678, maxFeePerGas: 2000000000 baseFee: 49196103287"
``` 

### Tasks
- [x] Investigate and fix the error described above

**Comment by valiafetisov** [comment]
I guess it's because of this line:
https://github.com/sidestream-tech/unified-auctions-ui/blob/cbf572753d9dde45d03ff63be8a62cbe03f70548/core/src/network.ts#L18

We either need to hardcode higher number to quickly fix it. Or check if it is properly estimated if there is no hardcoded number whatsoever.

**Comment by LukSteib** [comment]
> We either need to hardcode higher number to quickly fix it. Or check if it is properly estimated if there is no hardcoded number whatsoever.

Oh I see. I was expecting that we fetch the `baseFeePerGas` from the chain (in this case from Goerli) directly and then apply our calculation. 
We might open a PR removing the hardcoded number, check it and if the estimation is off fall back to just adding `0` to the harcoded number... 
Would you agree?

**Comment by valiafetisov** [comment]
Yes. Although adding a zero might be quite expensive 😢

**Comment by LukSteib** [comment]
> Yes. Although adding a zero might be quite expensive 😢

Well, looking at the number in the error message above adding a zero wouldn't even be enough ...

**Comment by valiafetisov** [comment]
Oh, true!
