### ISSUE TITLE
Fix problem wrongly displayed auctions

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#553]
### Goal
Only auctions of the selected network are displayed

### Context
We figured that switching network (in example case from `goerli` to `mainnet`) results in the situation that `goerli` auctions keep being displayed although the network both on UI and in wallet have been switched.
The problem can be replicated on staging as well as production 

We need to ensure that this is not the case as it can be very confusing for a user seeing auctions that shouldn't be there. 

### Tasks
- [ ] Investigate the problem of auctions being displayed for the wrong network
- [ ] Fix the problem 

### Assets
Problem replication:
https://www.loom.com/share/e4f33d1311c94427a603496ef0725481

**Comment by valiafetisov** [comment]
The quick solution would be to filter out auctions inside the getter by the currently selected network.

In other words, modify this getter and `filter()` by [`auctionTransaction.network`](https://github.com/sidestream-tech/unified-auctions-ui/blob/1d521133748e29ed466e0f719d5e8cc94bfed68d/core/src/types.ts#L10) and [getMakerNetwork](https://github.com/sidestream-tech/unified-auctions-ui/blob/1d521133748e29ed466e0f719d5e8cc94bfed68d/frontend/store/network.ts#L74)
https://github.com/sidestream-tech/unified-auctions-ui/blob/1d521133748e29ed466e0f719d5e8cc94bfed68d/frontend/store/auctions.ts#L55-L57
