### ISSUE TITLE
Include a link to the production environment inside the banner of the staging environment

### ISSUE THREAD

**Issue by florianstoecker** [sidestream-tech/unified-auctions-ui#61]
**Goal**
Have a link to the prod-environment included in the banner of the staging environment.

**Context**
As of #47, we only claim that the staging environment is not production. Instead, we should include a link to the production environment directly to point users to the right domain to participate.

**Tasks**
- [ ] Change the banner text from 
"This is a staging environment. Please use for testing purposes only." to 
"This is a staging environment for testing purposes only. The production is at https://auctions.makerdao.network/."

**Comment by valiafetisov** [comment]
The shorter version
```
This is a staging environment for testing purposes only. The production is at https://auctions.makerdao.network/.
```

**Comment by valiafetisov** [comment]
Note for the developer: `https://auctions.makerdao.network/` should probably come from an env variable and it would make sense to replace `IS_STAGING_ENVIRONMENT` with something like `STAGING_BANNER_URL`, which when not set result in no banner.
