### ISSUE TITLE
Deprecate surplus auctions and the 1inch callee

### ISSUE THREAD

**Issue by KirillDogadin-std** [sidestream-tech/unified-auctions-ui#611]
### Goal

Get rid of surplus auctions mechanism in the tool

### Context

As per the links in the assets - the surplus dai is not auctioned in return for MKR anymore. Instead it uses a different mechanism that does not involve "3rd party" participants to get rid of the surplus. Hence, functionality related to the surplus auctions is not needed in the tool.

### Assets

- [spell forum](http://forum.makerdao.com/t/introduction-of-smart-burn-engine-and-initial-parameters/21201)
- [spell executive vote](https://vote.makerdao.com/polling/QmQmxEZp#poll-detail)
- [clarification comment](http://forum.makerdao.com/t/introduction-of-smart-burn-engine-and-initial-parameters/21201/7)

### Tasks

- [ ] Confirm the above with team members
- [ ] Decide on actionables (probably removing the surplus auctions from the tool)
- [ ] Execute actionables

**Comment by KirillDogadin-std** [comment]
Suggested frontend adjustments:
 - remove the surplus related ui components from the main page on frontend
 - replace the contents of the `/surplus` auction page with "this page has been deprecated" kind of notification
 - Remove calls to the `surplus` store from the higher level stores

The whole process in #609 was not handled, so i would include it here to have the final working fix for everything broken. The problem is that the calls to oneinch api fail and information is not fetched properly. The error is not handled and the [request queue](https://github.com/sidestream-tech/unified-auctions-ui/blob/632575b03e60b8f43ba237117c7e8116cd2a9091/core/src/calleeFunctions/helpers/oneInch.ts#L57) gets stuck.

Suggested backend adjustment to address broken auction loading:
  - (minimal, must introduce) adjust the code [line that sends requests to oneinch api ](https://github.com/sidestream-tech/unified-auctions-ui/blob/632575b03e60b8f43ba237117c7e8116cd2a9091/core/src/calleeFunctions/helpers/oneInch.ts#L60) to account for errors because this introduces the infinite loading bug on frontend if the request is not successful
  - (optimal, would be nice) all above + refactor the code to throw less errors (either by catching them or introducing smarter retry mechanism) since the console looks all red if the minimal solution is introduced.
  - (maximal, best case) all above + figure out how to repair functionality that fetches prices from 1inch api.

**Comment by valiafetisov** [comment]
> Remove calls to the surplus store from the higher level stores

Yes

> remove the surplus related ui components from the main page on frontend
> replace the contents of the /surplus auction page with "this page has been deprecated" kind of notification

Yes, you can remove them, but please make sure the message is clear and contains a link for further info. Eg:
```
Note: surplus auctions are deprecated since the introduction of [smart burn engine](forum-url) via the [spell YYYY-MM-DD](executive-vote-url)
```

> Suggested backend adjustment to address broken auction loading

`maximal, best case` sounds good. But I would first make a fix `optimal, would be nice` in one PR and then repair it via the other one.

**Comment by KirillDogadin-std** [comment]
Additional info:

- oneinch has changed the api. The old one (that is currently used in the code) is deprecated and not accessible anymore. I've sent a request through CURL and got the corresponding error message.

```
curl 'https://api.1inch.io/v5.2/1/swap?fromTokenAddress=0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2&toTokenAddress=0x6B175474E89094C44Da98b954EedeAC495271d0F&fromAddress=0x19c916CDAFB41FAdd4CEd3dCf412e0302291563A&amount=7370000000000000000&slippage=1&allowPartialFill=false&disableEstimate=true&compatibilityMode=true' \
  -H 'sec-ch-ua: "Chromium";v="115", "Not/A)Brand";v="99"' \
  -H 'Referer: http://localhost:3000/' \
  -H 'DNT: 1' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'Authorization: Bearer SOMEBEARER' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --compressed
{"error":"Public API is not supported anymore. Please contact api@1inch.io to get an enterprise endpoint or test auth key."}% 
```
- i've adjusted the oneinch base endpoint in the code to `https://api.1inch.dev/swap/v5.2/${chainId}` and modified the code to also send the bearer token with the request. The responses arrive via the CURL. The frontend still is broken because faces the CORS issue. I did not see a functionality on the oneinch userdashboard to allow some origins to do cross-origin requests. I did not find documentation or other evidence suggesting that with enterprise version of oneinch api we would be able to set up the cors policy there.
