### ISSUE TITLE
Bidding with DAI mock

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#96]
### Goal
New mock for the `Bid with DAI` transaction type

### Tasks
- [x] Document existing flow at https://liquidations.makerdao.com
- [x] Create a new mock

**Comment by valiafetisov** [comment]
### Current flow
1. Attach a wallet
2. Authorize depositing DAI to VAT (a transaction)
3. Deposit DAI in VAT
    - Fetch user wallet balance
    - Fetch user VAT balance
    - Input field
      - Max button to prefill
      - Let user edit deposited amount
    - Deposit button (a transaction)
4. Bid with DAI
    - Fetch user VAT balance
    - Input field for the DAI amount
      - Button to fill it with total price of the auction
      - Button to fill it with all DAI in the VAT
    - Fetch and show `dust limit`
    - Show errors in case
      - Bid is smaller than `dust limit`
      - `Total - bid` is smaller than `dust limit`
    - Calculate amount of collateral user will receive
    - Execute button (disabled in case of errors from above)
5. Withdraw DAI
    - Fetch user wallet balance
    - Fetch user VAT balance
    - Input field
      - Max button to prefill
      - User can edit
    - Withdraw button (a transaction)
      - Disabled in case of the problem

### Screenshots
<img width="463" alt="Screenshot 2022-02-10 at 13 25 53" src="https://user-images.githubusercontent.com/3393626/153408471-1f20f9d9-c096-4755-b649-abff934ee386.png">
<img width="472" alt="Screenshot 2022-01-27 at 15 03 32" src="https://user-images.githubusercontent.com/3393626/151387065-860a982e-2635-481c-bb40-c8444d37c4fb.png">
<img width="463" alt="Screenshot 2022-01-27 at 15 04 35" src="https://user-images.githubusercontent.com/3393626/151386973-44a24111-badf-4eca-9862-1511c06d9326.png">
<img width="467" alt="Screenshot 2022-01-27 at 15 05 58" src="https://user-images.githubusercontent.com/3393626/151387000-a5329c28-8b68-40f7-8e81-a105f3967a40.png">
<img width="466" alt="Screenshot 2022-01-27 at 16 06 46" src="https://user-images.githubusercontent.com/3393626/151387007-cc4cdd14-73f6-43fd-a751-93e0e7446427.png">

**Comment by valiafetisov** [comment]
<details><summary>
Initial mock for the `Bid with DAI` transaction panel

</summary>

![MakerDAO@2x (2)](https://user-images.githubusercontent.com/3393626/153416225-509d8994-88e0-40bd-a080-726e32d5deb6.png)


</details>

https://whimsical.com/makerdao-7jmkXyT32KBtY4nQ56WARx

**Comment by LukSteib** [comment]
One further comment to `Withdraw` step in Whimsical

**Comment by valiafetisov** [comment]
Latest mock:

![MakerDAO@2x (16)](https://user-images.githubusercontent.com/3393626/155986690-36514df3-45a8-4713-9248-7114c7298def.png)

**Comment by valiafetisov** [comment]
Further mock iterations will be done in https://github.com/sidestream-tech/unified-auctions-ui/issues/145
